name: Build Release
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+-[RT]C[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get GitHub slug info
        uses: rlespinasse/github-slug-action@3.5.1

      - name: Pack it up!
        run: tar -czf /tmp/${{ github.event.repository.name }}-${{ env.GITHUB_SHA_SHORT }}-${{ env.GITHUB_REF_SLUG_CS }}.crbl data default LICENSE package.json README.md

      - name: Release
        if: ${{ success() }}
        id: release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, 'RC') || contains(github.ref, 'TC') }}
          files: /tmp/${{ github.event.repository.name }}-${{ env.GITHUB_SHA_SHORT }}-${{ env.GITHUB_REF_SLUG_CS }}.crbl
